### ISSUE TITLE
Gateways keep closing because of "wave entities spawning too far"

### ISSUE THREAD

**Issue by Mqony** [Shadows-of-Fire/GatewaysToEternity#24]
I noticed that you fixed an issue on version 3.1.0 on 1.19.2 that caused mobs to constantly spawn in invalid areas and therefore close the gateway. I don't know whether or not the 1.18.2 version is discontinued, but can you please consider fixing this bug in 1.18.2? This mod was going to be a core part of my modpack and it's pretty much unusable when gateways keep closing randomly. If you want to, you could also make it that you can specify in the JSON file whether or not you want to disable wormholes closing, but that's up to you.

Fixing this glitch would be greatly appreciated! Have a nice day!

**Comment by Shadows-of-Fire** [comment]
It wasn't really a fix per-se, spawning too far just means you've put the gateway in an invalid area which it can't find any suitable spawn locations for.

The 3.1.0 changes may make it back to 1.18, it depends on time constraints.

Anyhow, the fix for your issue is likely to reduce the spawn range of the gateway, or use it in a more open area. Gateways typically don't take well to being in enclosed spaces.

**Comment by Mqony** [comment]
Decreasing the spawn range seems to have mostly fixed the issue. Thanks.

**Comment by Mqony** [comment]
Is it possible to specify a "max range" value that determines how far mob has to be away from the gateway before the gateway closes?

**Comment by Shadows-of-Fire** [comment]
That would be the [leash range](https://gist.github.com/Shadows-of-Fire/a45a2742b7a0842c50738d3df3ce8148#file-21_gateway-js-L6)

**Comment by Mqony** [comment]
Thanks so much, it completely solved the problem!
